In [6]:
#Exo 1 
#With numpy

import numpy as np

A = np.array ([ [3,1,5], [9, 8, -1], [10, 12 ,2] ])
B = np.array ([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])

C= A+B
print("A : ",A)
print("B : ",B)
print("A + B : ",C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [10 12  2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A + B :  [[11  0 13]
 [11  9  2]
 [28 14 34]]


In [ ]:
#Exo 1 
#Without numpy

X = [ [3, 1, 5], 
    [9, 8, -1], 
    [10, 12 ,2] ]

Y = [ [8, -1, 8], 
    [2, 1, 3], 
    [18, 2, 32] ]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range (len(x)):
    for j in range (len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
        

In [7]:
#Exo 2 

import numpy as np

A = np.array ([ [3, 1, 5], [9, 8, -1], [10, 12 ,2] ])
B = np.array ([ [8, -1, 8], [2, 1, 3], [18, 2, 32] ])

C = A.dot(B)

print("A : ", A)
print("B : ", B)
print("A * B : ", C)

A :  [[ 3  1  5]
 [ 9  8 -1]
 [10 12  2]]
B :  [[ 8 -1  8]
 [ 2  1  3]
 [18  2 32]]
A * B :  [[116   8 187]
 [ 70  -3  64]
 [140   6 180]]


In [11]:
#Ex3
def eststochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est stochastique
    for i in range(nl):
        s = 0
        for j in range(nc):
            s += P[i][j]
        if s > 1:
            etat = False
            break
    return etat
 
 
def estbistochastique(P):
    nl = len(P)  # nombre de lignes
    nc = len(P[0])  # nombre de colonnes
 
    etat = True  # on suppose que la matrice est bistochastique
    if(eststochastique(P)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += P[i][j]
            if s > 1:
                etat = False
                break
    return etat
 
 
def vecteurstable(G, h):
    nl = len(G)  # nombre de lignes
    nc = len(G[0])  # nombre de colonnes
    etat = True
    if(eststochastique(G)):
        for j in range(nc):
            s = 0
            for i in range(nl):
                s += h[i]*G[i][j]
            if s != h[j]:
                etat = False
                break
    else:
        etat = False
    return etat

In [9]:
#Exo 4

import numpy as np

A= np.array([ [3, 1, 5], [9, 8, -1], [24, 12 ,2] ])

C = A.transpose()

print("A : ", A)
print("Transposée de A : ",C)


A :  [[ 3  1  5]
 [ 9  8 -1]
 [24 12  2]]
Transposée de A :  [[ 3  9 24]
 [ 1  8 12]
 [ 5 -1  2]]


In [ ]:
#Ex5
# appliquer une permutation
def apply_permutation(A,perm,N):
    B=np.empty_like(A) # A est une matrice NxN d'entiers dans range(N)
    for i in range(N):
            B[A[:]==i]=perm[i] # perm est une permutation de range(N)
    return B